blank_issues_enabled: true
contact_links:
  - name: New Icon Suggestion
    url: https://github.com/tailwindlabs/heroicons/discussions/new?category=ideas
    about: Have a suggestion for a new icon? Do it here!
