name: Publish
on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install

      - run: yarn build

      - run: node ./scripts/set-package-version.js react/package.json

      - run: npm publish
        working-directory: react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'

      - run: npm publish
        working-directory: react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
